services:
  app:
    container_name: yddy_hdd
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./database:/resources
    restart: always
    environment:
      - CGO_ENABLED=1
      - PORT=8080