version: '3.3'
services:
  yddy_hdd:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./database:/resources
    restart: always
    environment:
      - CGO_ENABLED=1
      - PORT=8080